### ISSUE TITLE
The external does not build on the Raspberry Pi - asio error

### ISSUE THREAD

**Issue by lucaturchet** [libpd/abl_link#34] opened 2022-09-30 08:21 UTC
Hello, I am trying to build the abl_link~ external on a raspberry Pi 4, but I get some errors related to the actual cpp code. I am not sure if it is a matter related to libpd, it seems that the errors are related to the syntax itself. After launching 
`make -j4 PDINCLUDEDIR=/usr/local/include/pd`

I get the error:

`abl_link~.cpp: In function 'void abl_link_tilde_reset(t_abl_link_tilde*, t_symbol*, int, t_atom*)':
abl_link~.cpp:116:7: error: 'error' was not declared in this scope; did you mean 'asio::error'?
  116 |       error("abl_link~ reset: Unexpected number of parameters: %d", argc);
      |       ^~~~~
      |       asio::error`

and then:

`abl_link~.cpp: In function 'void* abl_link_tilde_new(t_symbol*, int, t_atom*)':
abl_link~.cpp:143:7: error: 'error' was not declared in this scope; did you mean 'asio::error'?
  143 |       error("abl_link~: Unexpected number of creation args: %d", argc);
      |       ^~~~~
      |       asio::error`

Could you please provide some guidance?

**Comment by umlaeute** [comment] 2022-09-30 21:02
this is a duplicate of #29, and has been fixed with #30.

Also, on Raspbian you should be able to simply install the `pd-ableton-link` package with apt.

**Closed by umlaeute** 2022-09-30 21:02 UTC
Labels: duplicate
